sudo: required
services:
  - docker

before_install:
  - docker build -t rbuzatto/docker-react -f Dockerfile.dev .

script:
  - docker run rbuzatto/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-499960346725"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $ACCESS_KEY
  secret_access_key:
    secure: "$SECRET_KEY"